import React,{useEffect,useMemo,useRef,useState}from'react';
import{ActivityIndicator,Alert,FlatList,KeyboardAvoidingView,Linking,Platform,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,View}from'react-native';
import*as SecureStore from'expo-secure-store';import*as Device from'expo-device';import*as Application from'expo-application';import NetInfo from'@react-native-community/netinfo';
import{Camera,useCameraDevice,useCameraPermission,useFrameProcessor}from'react-native-vision-camera';import{scanOCR}from'react-native-vision-camera-ocr-plus';import{Worklets}from'react-native-worklets-core';
import{api,message}from'./src/api';
const G='#176b43',BG='#eef1ef';
const clean=v=>String(v||'').trim().replace(/[^A-Za-z0-9-]/g,'');
const Button=({title,onPress,disabled,outline})=><Pressable disabled={disabled} onPress={onPress} style={[s.btn,outline&&s.outline,disabled&&{opacity:.5}]}><Text style={[s.btnText,outline&&{color:G}]}>{title}</Text></Pressable>;
const Field=({label,...p})=><View style={{marginBottom:12}}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor="#89918d" style={s.input}{...p}/></View>;
const Card=({children})=><View style={s.card}>{children}</View>;
export default function App(){const[screen,setScreen]=useState('loading'),[session,setSession]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[config,setConfig]=useState(null);const[form,setForm]=useState({mobile_user_id:'',password:'',pairing_code:''});
useEffect(()=>{boot()},[]);async function boot(){const t=await SecureStore.getItemAsync('device_session');if(!t)return setScreen('pair');try{const r=await api.get('/session');setSession(r.data);const c=await api.get('/config',{params:{app_version:Application.nativeApplicationVersion||'1.0.0'}});setConfig(c.data);setScreen(c.data.latest_version?.mandatory_update&&c.data.latest_version.version_name!==(Application.nativeApplicationVersion||'1.0.0')?'update':'home')}catch(e){await SecureStore.deleteItemAsync('device_session');setScreen('pair')}}
async function pair(){setBusy(true);setError('');try{let id=await Application.getAndroidId();id=id||`${Device.modelName}-${Date.now()}`;const r=await api.post('/pair',{...form,device_id:id,device_name:Device.deviceName||Device.modelName||'Android',android_info:{brand:Device.brand,model:Device.modelName,os:Device.osVersion},app_version:Application.nativeApplicationVersion||'1.0.0'});await SecureStore.setItemAsync('device_session',r.data.session_token);await SecureStore.setItemAsync('device_id',id);await boot()}catch(e){setError(message(e))}finally{setBusy(false)}}
if(screen==='loading')return <SafeAreaView style={s.center}><ActivityIndicator color={G}/></SafeAreaView>;
if(screen==='pair')return <SafeAreaView style={s.root}><StatusBar backgroundColor={G}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}><ScrollView contentContainerStyle={s.wrap}><Text style={s.logo}>Sleeping Stock</Text><Text style={s.title}>Mobile Pairing</Text><Text style={s.sub}>Enter the Mobile User credentials and the one-time code generated in NMTS Web.</Text><Card><Field label="Mobile User ID" autoCapitalize="characters" value={form.mobile_user_id} onChangeText={v=>setForm({...form,mobile_user_id:v.trim().toUpperCase()})}/><Field label="Password" secureTextEntry value={form.password} onChangeText={v=>setForm({...form,password:v})}/><Field label="Manual Pairing Code / QR Payload" autoCapitalize="characters" value={form.pairing_code} onChangeText={v=>setForm({...form,pairing_code:v})}/>{error?<Text style={s.err}>{error}</Text>:null}<Button title={busy?'Pairing...':'Pair Device'} disabled={busy||!form.mobile_user_id||!form.password||!form.pairing_code} onPress={pair}/></Card></ScrollView></KeyboardAvoidingView></SafeAreaView>;
if(screen==='update')return <SafeAreaView style={s.center}><Card><Text style={s.title}>New Update Available</Text><Text style={s.sub}>{config?.latest_version?.release_notes||'Install the latest approved build to continue.'}</Text><Button title="Open NMTS APK Download" onPress={()=>Linking.openURL(config?.latest_version?.download_url||'https://sleepingstock.in')}/></Card></SafeAreaView>;
return <Main session={session} go={setScreen} screen={screen} logout={async()=>{await SecureStore.deleteItemAsync('device_session');setScreen('pair')}}/>}
function Main({session,go,screen,logout}){if(screen==='home')return <SafeAreaView style={s.root}><View style={s.header}><View><Text style={s.headerTitle}>Sleeping Stock Mobile</Text><Text style={s.headerSub}>{session?.mobile_user?.branch_name}</Text></View><Pressable onPress={logout}><Text style={{color:'white'}}>Reset</Text></Pressable></View><ScrollView contentContainerStyle={s.wrap}><Text style={s.welcome}>Welcome, {session?.mobile_user?.name}</Text>{[['Notifications','notifications'],['Stock Verification','verify'],['Stock Search','search']].map(([a,b])=><Pressable key={b} style={s.menu} onPress={()=>go(b)}><Text style={s.menuText}>{a}</Text><Text style={s.arrow}>›</Text></Pressable>)}</ScrollView></SafeAreaView>;
return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>go('home')}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.headerTitle}>{screen==='notifications'?'Notifications':screen==='verify'?'Stock Verification':screen==='scanner'?'Camera OCR':'Stock Search'}</Text><View/></View>{screen==='notifications'?<Notifications/>:screen==='verify'?<Verification go={go}/>:screen==='scanner'?<Scanner go={go}/>:<Search/>}</SafeAreaView>}
function Notifications(){const[rows,setRows]=useState([]),[busy,setBusy]=useState(true);const load=async()=>{try{setRows((await api.get('/notifications')).data)}catch(e){Alert.alert('Unable to load',message(e))}finally{setBusy(false)}};useEffect(()=>{load()},[]);const act=async(id,type)=>{try{await api.post(`/notifications/${id}/${type}`,{});load()}catch(e){Alert.alert(type==='accept'?'Accept failed':'Skip failed',message(e))}};if(busy)return <ActivityIndicator style={{marginTop:40}} color={G}/>;return <FlatList contentContainerStyle={s.wrap} data={rows} keyExtractor={(x,i)=>x.id||String(i)} ListEmptyComponent={<Text style={s.sub}>No active requests for this Branch.</Text>} renderItem={({item})=><Card><Text style={s.cardTitle}>{item.request_number||item.id}</Text><Text>Reference: {item.order_number||'-'}</Text><Text>Total Qty: {item.quantity||item.requested_qty||0}</Text><Text>Status: {item.status}</Text><Text>Skips: {item.skip_count||0}/2</Text><View style={s.row}><Button title="Accept" onPress={()=>act(item.id,'accept')}/><Button title="Skip" outline disabled={!item.skip_allowed} onPress={()=>act(item.id,'skip')}/></View></Card>}/>}
function Verification({go}){const[f,setF]=useState({part_number:'',physical_quantity:'',location:'',remark:'',entry_method:'MANUAL'}),[busy,setBusy]=useState(false);useEffect(()=>{global.__setScannedPart=v=>setF(x=>({...x,part_number:v,entry_method:'CAMERA_OCR'}));return()=>{delete global.__setScannedPart}},[]);const submit=async()=>{setBusy(true);try{await api.post('/stock-verifications',{...f,physical_quantity:Number(f.physical_quantity)});Alert.alert('Saved','Verification stored as a separate history record.');setF({part_number:'',physical_quantity:'',location:'',remark:'',entry_method:'MANUAL'})}catch(e){Alert.alert('Unable to submit',message(e))}finally{setBusy(false)}};return <ScrollView contentContainerStyle={s.wrap}><Card><Field label="Part Number" value={f.part_number} onChangeText={v=>setF({...f,part_number:v.toUpperCase(),entry_method:'MANUAL'})}/><Button title="Open Camera OCR" outline onPress={()=>go('scanner')}/><Field label="Physical Quantity" keyboardType="decimal-pad" value={f.physical_quantity} onChangeText={v=>setF({...f,physical_quantity:v})}/><Field label="Location" value={f.location} onChangeText={v=>setF({...f,location:v})}/><Field label="Remark (Optional)" multiline value={f.remark} onChangeText={v=>setF({...f,remark:v})}/><Button title={busy?'Submitting...':'Submit Verification'} disabled={busy||!f.part_number||f.physical_quantity===''} onPress={submit}/></Card></ScrollView>}
function Scanner({go}){const device=useCameraDevice('back');const{hasPermission,requestPermission}=useCameraPermission();const[scanRequested,setScanRequested]=useState(false),[detected,setDetected]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{if(!hasPermission)requestPermission()},[hasPermission]);const onResult=useMemo(()=>Worklets.createRunOnJS(t=>{setBusy(false);setScanRequested(false);setDetected(clean(t));}),[]);const fp=useFrameProcessor(frame=>{'worklet';if(!scanRequested)return;const result=scanOCR(frame);const text=(result?.resultText||result?.text||'').trim();onResult(text)},[scanRequested]);if(!hasPermission)return <View style={s.center}><Text>Camera permission denied. Use manual entry.</Text><Button title="Back" onPress={()=>go('verify')}/></View>;if(!device)return <View style={s.center}><Text>Camera unavailable.</Text></View>;return <View style={{flex:1}}><Camera style={StyleSheet.absoluteFill} device={device} isActive frameProcessor={fp}/><View style={s.roi}/><View style={s.scanPanel}><Button title={busy?'Scanning...':'Scan'} disabled={busy} onPress={()=>{setDetected('');setBusy(true);setScanRequested(true);setTimeout(()=>{setBusy(false);setScanRequested(false)},2500)}}/>{detected?<Pressable onPress={()=>{global.__setScannedPart?.(detected);go('verify')}}><Text style={s.detected}>{detected}</Text></Pressable>:<Text style={{color:'white',textAlign:'center'}}>Align the complete Part Number inside the box, then tap Scan. Text not detected will leave this blank.</Text>}</View></View>}
function Search(){const[text,setText]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{const parts=text.split(/\r?\n/).map(clean).filter(Boolean);setRows((await api.post('/stock-search',{part_numbers:parts})).data)}catch(e){Alert.alert('Search failed',message(e))}finally{setBusy(false)}};return <ScrollView contentContainerStyle={s.wrap}><Card><Field label="Part Numbers (one per line)" multiline value={text} onChangeText={setText}/><Button title={busy?'Searching...':'Search Branch Stock'} disabled={busy||!text.trim()} onPress={run}/></Card>{rows.map((r,i)=><Card key={r.part_number+i}><Text style={s.cardTitle}>{r.part_number}</Text><Text>{r.part_name||r.item_name}</Text><Text>Available: {r.quantity||0}</Text><Text>Location: {r.location||r.loc||'-'}</Text><Text>Category: {r.part_category||r.category||'-'}</Text></Card>)}</ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:BG},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:BG,padding:24},wrap:{padding:18,gap:14},header:{backgroundColor:G,padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},headerTitle:{color:'white',fontWeight:'800',fontSize:18},headerSub:{color:'#dbece4'},back:{color:'white',fontWeight:'700'},logo:{fontSize:30,fontWeight:'900',color:G,textAlign:'center',marginTop:35},title:{fontSize:24,fontWeight:'800',color:'#25312c',textAlign:'center',marginTop:8},sub:{color:'#67716c',textAlign:'center',marginVertical:10,lineHeight:21},welcome:{fontSize:20,fontWeight:'800'},card:{backgroundColor:'white',padding:16,borderRadius:16,borderWidth:1,borderColor:'#d9dfdc',gap:8},cardTitle:{fontWeight:'800',fontSize:17,color:'#24322b'},label:{fontSize:12,fontWeight:'700',color:'#51605a',marginBottom:5},input:{borderWidth:1,borderColor:'#cbd3cf',borderRadius:10,paddingHorizontal:12,paddingVertical:11,color:'#18221d',backgroundColor:'#fafcfb'},btn:{backgroundColor:G,borderRadius:10,paddingVertical:12,paddingHorizontal:16,alignItems:'center',minWidth:110,marginTop:8},outline:{backgroundColor:'white',borderWidth:1,borderColor:G},btnText:{color:'white',fontWeight:'800'},err:{color:'#b42318'},menu:{backgroundColor:'white',borderRadius:16,padding:22,borderWidth:1,borderColor:'#d4dbd7',flexDirection:'row',justifyContent:'space-between'},menuText:{fontSize:20,fontWeight:'800',color:'#26342d'},arrow:{fontSize:30,color:G},row:{flexDirection:'row',gap:10,flexWrap:'wrap'},roi:{position:'absolute',left:'8%',right:'8%',top:'30%',height:150,borderWidth:3,borderColor:'#7ee2aa',borderRadius:12},scanPanel:{position:'absolute',left:16,right:16,bottom:25,gap:12},detected:{backgroundColor:'white',padding:14,borderRadius:10,textAlign:'center',fontWeight:'800',fontSize:18,color:G}});
