plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'in.sleepingstock.mobile'
version = '1.0.0'

android {
  namespace "in.sleepingstock.mobile.requestalert"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'com.google.firebase:firebase-messaging:24.0.1'
  implementation 'androidx.core:core:1.13.1'
}
